# Config file for Beaconz
defaultlocale: en-US

world:
  # Beaconz world
  name: beaconz   
  
  # Default game name
  defaultgamename: Beaconz
  
  # Distribution of beacons the large the number, the more beacons are made
  distribution: 0.03
  
  # Distance between new game regions. Must be at least size of the barrier
  # This is the default size for the sides of each new (square) game region
  distance: 2000
  
  # Number of seconds a player must be stationary before they will be teleported
  teleportdelay: 5 

  # Lobby settings
  # Coordinates for the lobby area
  # These coordinates must be divisible by 16, otherwise they will be adjusted
  lobbyx: 0
  lobbyz: 0
  lobbyradius: 16 
  # Lobby platform will be at this height
  lobbyheight: 200
  # Lobby platform will be made up randomly of these blocks. Tip: Mobs do not spawn on glass.
  # You can replace the lobby after it is made.
  lobbyblocks:
  - STAINED_GLASS:2
  - STAINED_GLASS:3
  - STAINED_GLASS:4
  - STAINED_GLASS:5
  
  # Starting point for first game
  xcenter: 2000
  zcenter: 2000
  
  # Team chat
  # If true, players can only converse with their team players in the beaconz world
  teamchat: false
  
  # Number of blocks that each exp point will link when linking a beacon
  # If zero, there is no exp cost to link beacons
  expdistance: 5
  
  # The maximum distance a beacon can link without extending link blocks
  linklimit: 500
  
  # Link blocks that extend the link limit, and by how much. Once a link block is placed
  # it cannot be removed without losing the longest link from the beacon
  # Link blocks count from both ends of the link.
  linkblocks:
     GOLD_BLOCK: 50
     DIAMOND_BLOCK: 200
     
  # Remove the longest link if a range extender block is removed.
  # This is a penalty for breaking link blocks, but can be used by the owning team
  # to remove links so they can be make elsewhere at the cost of gold blocks and
  # losing links in order of length (quite a cost!)
  # Default is not to lose a link.
  removelongestlink: false
  
  # Destroy link blocks completely when they are removed
  # Default is true. This is not recommended to be false otherwise players can reuse
  # blocks between beaconz. Essentially, extending a beacon link length consumes blocks.
  destroylinkblocks: true
  
  # What will be given to the player when they make a link 
  # Material:Durability:Quantity - all three are mandatory
  # For potions, POTION:NAME:<LEVEL>:<EXTENDED>:<SPLASH/LINGER>:QTY
  linkrewards:
  - EMERALD:0:1
  
  # Link commands
  # Commands that will be run when the player makes a link. Command is run as console.
  # [player] is the linking player
  # If the command is proceeded by [SELF] the command will be run as that player
  # E.g., - "[SELF] kit tools"
  linkcommands:
  #- "give [player] emerald 1"
  #- "some other command"
  
  # Maximum number of links a beacon can have. Note teams cannot remove their own links
  # except by sacrificing link extender blocks.
  maxlinks: 6
  
  # Defense height - max height of blocks that can be placed around a beacon to defend it
  defenseheight: 8
  
  # Defense levels
  # Defines what exp levels is required to place a block at that height around the beacon
  # Height: Exp level
  defenselevel:
     1: 0
     2: 2
     3: 5
     4: 10
     5: 15
     6: 20
     7: 25
     8: 30
   
  # Removal level delta  
  # Players can only remove defense blocks they place unless they are this many levels
  # higher than the defense level. For example, if this is 5, then level 35 players can
  # remove any block placed level 30 or below.
  # If zero, players can remove any defense block on the beacon
  # If -1, players can only remove defense blocks they placed
  removaldelta: -1

  # Attack levels
  # Defines what exp level an attacker must be to be able to mine the block at that height
  # Height: Exp level 
  attacklevel:
     1: 0
     2: 2
     3: 5
     4: 10
     5: 15
     6: 20
     7: 25
     8: 30  

  # Starter inventory
  # Format Material:Qty or Material:Data:Qty
  # Note that any type of pickaxe can eventually break obsidian.
  newbiekit:
  - "DIAMOND_PICKAXE:1"
  - "BREAD:2"
  
  # Beacon mine settings
  # Cost in experience points to mine a beacon
  beaconmineexp: 10
  
  # Chance % that mining a beacon will result in it becoming exhausted and enter
  # a cool down period.
  beaconmineexhaustchance: 50
  
  # Mine cool down period in minutes
  minecooldown: 1
  
  # Cooldown period penalty
  # Players get this if they mine during the cooldown until the cooldown finishes.
  # Format is Effect:Amplifier
  # Options are: Blindness, Confusion, Harm, Hunger, Slow, Slow_digging, Weakness, Wither
  # Amplifier is a number, .e.g, 0, 1
  minepenalty:
  - "SLOW_DIGGING:1"

  # Rewards from mining beaconz
  # Format is "Id#/Material:[Durability/Qty]:Qty=%Chance"
  # Reward from mining an enemy beacon. Generally the idea is to give players an
  # incentive to find enemy beaconz and even if they cannot attack them, to mine them
  # Goodies are items not normally available because they are from the nether or end or rare.
  enemygoodies:
  - "EMERALD:1=1"
  - "NETHER_STALK:1=5"
  - "SOUL_SAND:1=10"
  - "GHAST_TEAR:1=1"
  - "BLAZE_ROD:1=2"
  - "GLOWSTONE:1=5"
  - "NETHERRACK:4=20"
  - "SPECTRAL_ARROW:1=5"
  - "ENDER_STONE:1=1"
  - "CHORUS_FLOWER:1=1"
  - "QUARTZ_ORE:1=10"
  
  # Mining your own beacon should give you the chance of obtaining a map
  teamgoodies:
  # The map is a beacon map. Give empty map if you want to give a normal map
  - "MAP:1=100"

  # Effects from going into enemy triangle fields
  # Effects are cumulative, i.e., level 2 includes level 1 effects.
  enemyfieldeffects:
    # When in 1 field
    1:
    # Format is "Effect:Amplifier"
    - "SLOW:1"
    # When in 2 fields
    2:
    - "SLOW_DIGGING:1"
    3:
    - "WEAKNESS:1"
    4:
    - "HUNGER:2"
    5:
    - "CONFUSION:1"
    6:
    - "POISON:1"
    7:
    - "BLINDNESS:1"
    8:
    - "WITHER:1"
  friendlyfieldeffects:
    1:
    - "SPEED:1"
    2:
    - "DAMAGE_RESISTANCE:1"
    3:
    - "FAST_DIGGING:1"
    4:
    - "JUMP:1"
    5:
    - "REGENERATION:1"
    6:
    - "HEALTH_BOOST:1"
    7:
    - "NIGHT_VISION:1"
    8:
    - "INVISIBILITY:1"

# Team configuration
default_teams: 2
# Teams have glass colors that can be picked from these. They must be different.
# Team names can be anything you like, but must be a single word
# 0: White Stained Glass
# 1: Orange Stained Glass
# 2: Magenta Stained Glass
# 3: Light Blue Stained Glass
# 4: Yellow Stained Glass
# 5: Lime Stained Glass
# 6: Pink Stained Glass
# 7: Gray Stained Glass
# 8: Light Gray Stained Glass
# 9: Cyan Stained Glass
# 10: Purple Stained Glass
# 11: Blue Stained Glass
# 12: Brown Stained Glass
# 13: Green Stained Glass
# 14: Red Stained Glass
# 15: Black Stained Glass
teams:
  red:
    displayname: "Red"
    glasscolor: 14
  blue:
    displayname: "Blue"
    glasscolor: 11
  white:
    displayname: "White"
    glasscolor: 0
  lightblue:
    displayname: "Aqua"
    glasscolor: 3
  yellow:
    displayname: "Yellow"
    glasscolor: 4
  lime:
    displayname: "Lime"
    glasscolor: 5
  gray:
    displayname: "Gray"
    glasscolor: 7
  lightgray:
    displayname: "Mist"
    glasscolor: 8
  cyan:
    displayname: "Cyan"
    glasscolor: 9       
  purple:
    displayname: "Purple"
    glasscolor: 10
  brown:
    displayname: "Brown"
    glasscolor: 12
  green:
    displayname: "Green"
    glasscolor: 13
  black:
    displayname: "Black"
    glasscolor: 15
  orange:
    displayname: "Orange"
    glasscolor: 1
  magenta:
    displayname: "Magenta"
    glasscolor: 2
  pink:
    displayname: "Pink"
    glasscolor: 6   
        
# gamemode is strategy or minigame
# Strategy is a long running game, maybe infinitely running
# minigame is meant to run for a few minutes and then reset
gamemode: strategy

# Sidebar scoreboard options: area, beacons, links, triangles
# remember that the sidebar only has 15 lines, if there are too many teams there will not be enough room to display everything
sidebar:
  minigame: area:beacons:links:triangles
  strategy: area:beacons:links:triangles

# Goal to win the game
# The goal must be one of the scores displayed on the sidebar
# a goal value > 0 means the game ends when a team reaches that score; the timer is open-ended and counts up
# a goal value = 0 means the timer counts down and when it reaches 0 the team with the greatest score for that goal wins   
goals:
  minigame: area:20000
  strategy: area:3000000

# Timer in seconds, for when the goal value is greater than zero 
timer:
  minigame: 600
  strategy: 0 

# Use dynmap overlay (require dynmap plugin)
# This is useful and cool for admins, but gives too much info to players.
# See dynmap.yml for settings.
usedynmap: false
